repository: aicoder
contexts:
  default:
    target_path:
    exclude:
      - ent
      - go.sum
      - repo_structure.json
    include:
      - ent/schema
current_context: default
search:
  top_n: 10
