coverage:
  status:
    project:
      target: 0%
      threshold: 0%
    patch:
      target: 0%
      threshold: 0%

# sample regex patterns
ignore:
  - "ent"  # ignore folders and all its contents
