// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DocumentsColumns holds the columns for the "documents" table.
	DocumentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "repository", Type: field.TypeString, Size: 2147483647},
		{Name: "context", Type: field.TypeString, Size: 2147483647},
		{Name: "filepath", Type: field.TypeString, Size: 2147483647},
		{Name: "description", Type: field.TypeString, Size: 2147483647},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "embedding", Type: field.TypeOther, SchemaType: map[string]string{"postgres": "vector(1536)"}},
	}
	// DocumentsTable holds the schema information for the "documents" table.
	DocumentsTable = &schema.Table{
		Name:       "documents",
		Columns:    DocumentsColumns,
		PrimaryKey: []*schema.Column{DocumentsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "document_embedding",
				Unique:  false,
				Columns: []*schema.Column{DocumentsColumns[6]},
				Annotation: &entsql.IndexAnnotation{
					OpClass: "vector_l2_ops",
					Type:    "hnsw",
				},
			},
			{
				Name:    "document_repository_context_filepath",
				Unique:  true,
				Columns: []*schema.Column{DocumentsColumns[1], DocumentsColumns[2], DocumentsColumns[3]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DocumentsTable,
	}
)

func init() {
}
